### ISSUE TITLE
[Ulepszenie] Otwieranie plików przy upuszczeniu na program

### ISSUE THREAD

**Issue by kostek00** [bjakja/Kainote#15]
Upuszczanie plików w zakładce (czerwona strefa) mogłoby je otwierać w aktywnej zakładce. Upuszczanie plików wszędzie poza zakładką mogłoby otwierać je w nowej zakładce. Upuszczanie wielu plików o różnych nazwach jak do tej pory, otwieranie w nowych zakładkach.

![upuszczanie](https://user-images.githubusercontent.com/6637173/32397490-5600ca22-c0ea-11e7-9da8-91512851d5b2.png)

**Comment by bjakja** [comment]
To jest bardzo ciekawe, bo myślałem, że tak właśnie to działa, a nawet upuszczenie na nieaktywną zakładkę otwiera to właśnie w niej. Upuszczenie na pustą część paska zakładek otwiera w nowym oknie, Jeśli to nie działa w ten sposób, to jest raczej bug.

**Comment by kostek00** [comment]
Tak właśnie działa, ale tylko na pasku zakładek. Cała reszta programu jest traktowana jako zawartość zakładki.
