### ISSUE TITLE
[Błąd] Otwieranie pliku napisów

### ISSUE THREAD

**Issue by kostek00** [bjakja/Kainote#16]
Gdy są wczytane do programu napisy i wideo, a następnie znowu otworzy się te same napisy (dowolna metoda) powoduje nie wczytanie automatycznie pliku wideo. Wczytuje same napisy. Gdy natomiast są otwarte tylko napisy i otworzy się je ponownie (dowolna metoda), wtedy jest już wczytywany plik wideo.

Windows 8.1, Kainote 0.9.1.779

**Comment by bjakja** [comment]
Normalnie zablokowałem wczytywanie tego samego wideo, jeśli wideo jest inne od tego, które mamy wczytane, to wiadomo trzeba je wczytać, ale jeśli to samo wideo, po co drugi raz je wczytywać?

**Comment by kostek00** [comment]
Chociażby, żeby coś porównać.

**Comment by bjakja** [comment]
Naprawione po dodaniu zapisu ścieżek wideo / audio do napisów
