### ISSUE TITLE
Ładowanie wykresu w locie

### ISSUE THREAD

**Issue by MatiasMovie** [bjakja/Kainote#172]
Ładowanie wykresu audio i klatek kluczowych w locie, tak jak audio się ładuje, nie dopiero po załadowaniu całego audio

**Comment by bjakja** [comment]
Ta możliwość jest osiągalna tylko przy zapisie do pamięci, bo funkcje dysku nie obsługują jednoczesnego zapisu i odczytu, a próba zabezpieczenia sekcją krytyczną i tak na niewiele się zdała, bo zaś odczyt w ogóle nie mógł się wykonać. Zamykam ten issue jako nieosiągalny w tym przypadku.
