### ISSUE TITLE
[Ulepszenie] Otwieranie wielu plików z menu

### ISSUE THREAD

**Issue by kostek00** [bjakja/Kainote#18]
Przydałoby się gdyby dało się otwierać wiele plików z menu. Np. przy „otwórz napisy” można by zaznaczyć wiele plików napisów i otwierałoby je tak samo jak w przypadku upuszczenia wielu plików napisów na program czy zaznaczenie w folderze plików z napisami i otwarcie ich. To samo dotyczy innych opcji zawierających operację „otwórz”.

**Comment by bjakja** [comment]
Zorientowałem się w temacie i to wymaga dodanie jednej flagi i użycia innej funkcji by pobrać nazwy, ale ogólnie więcej przeróbek jest wymagane więc odłożę to ulepszenie do czasu merge grid refactory do mastera.
