### ISSUE TITLE
Nazwa ścieżki audio 'aac'

### ISSUE THREAD

**Issue by MatiasMovie** [bjakja/Kainote#180]
Wyświetlanie nazwy aac zamiast języka audio

**Comment by MatiasMovie** [comment]
[Kopimi-Commie][Shakugan No Shana III -Final-][01][BDRIP][HEVC][Hi10p AAC][Dual-Audio][1920X1080].mkv

**Comment by bjakja** [comment]
To fix this bug I have to use newer matroska parser. To fix this bug I need compile ffmpeg and use its matroska parser that is split to many files.
