### ISSUE TITLE
[Błąd] Błędne wyświetlanie tłumaczenia - tryb tłumacza

### ISSUE THREAD

**Issue by kostek00** [bjakja/Kainote#21]
W trybie tłumacza napisanie czegoś w polu tłumaczenia zanim linijka zostanie wyświetlona powoduje wyświetlenie tylko pierwszego znaku.

**Comment by bjakja** [comment]
http://imagizer.imageshack.com/img924/3544/FwLutN.png
prawdopodobnie gdzieś zawodzi wczytywanie visible to end, bo przy rozpoczęciu odtwarzania powinno zapisać linie widoczne do samego końca, jeśli tego nie zrobiło prawdopodobnie jedna zmienna jest na false.
