### ISSUE TITLE
[Regression] Gridrefactory

### ISSUE THREAD

**Issue by kostek00** [bjakja/Kainote#24]
- [x] 1. Dopóki nie będzie można tworzyć więcej niż jeden filtr według zaznaczeń to niekoniecznie będzie to użyteczne, reszta niekoniecznie. Np. według stylów tylko po jednym na każdy styl.

- [x] 2. Przy filtrowaniu pierwszej linijki od góry (i tylko tej jednej) linia biegnąca od plusa w dół nie skręca w prawo.

- [x] 3. Przy włączonym trybie tłumacza filtrowanie według niepewnych, których nie ma żadnych pokazuje pusty pasek na którym jest plus.

- [x] 4. Przy włączonym trybie tłumacza w którym nie ma żadnego tłumaczenia filtrowanie według nieprzetłumaczonych ukrywa wszystko bez pokazania plusa na rozwinięcie.
        -> Przy wszystkich linijkach ukrytych na gridzie nadal pozostaje obramowanie aktywnej linijki.

- [x] 5. Po włączeniu filtrowania według nieprzetłumaczonych, a następnie wyłączeniu trybu tłumacza linijki nadal pozostają ukryte. Po wyłączeniu trybu tłumacza powinno wyłączać filtrowanie według niepewnych i nieprzetłumaczonych, a następnie pokazać filtrowane linijki.
        -> Jeżeli wyłączy się tryb tłumacza po włączeniu filtrowania według nieprzetłumaczonych, a następnie zacznie cofać zmiany to linijki w których zostały cofnięte zmiany zostają wyświetlane. Po przywracaniu zmian linijki znowu zostają ukryte.

- [x] 6. Gdy po wprowadzeniu zmian w tekst włączy się tryb tłumacza, a następnie włączy filtrowanie na linijkach ze zmianami i cofnie zmiany, a następnie na tych linijkach jeszcze raz włączy sie filtrowanie to nie będzie możliwe już przywracanie cofniętych zmian. (Tylko tryb tłumacza wykazał ten błąd z filtrowaniem na nieprzetłumaczonych i niepewnych, możliwe, że ma to związek z faktem, że zostały ukryte wszystkie linijki.)

- [x] 7. Nowo utworzona linijka zaraz za lub przed filtrem zostaje dodana do filtru. Dodatkowo gdy zostaje ona utworzona przed filtrem to dostaje ona również plusa przez co można ukrywać w dziwny sposób te linijki, a rysowanie linii wychodzącej od plusa dorysowuje się w miejscach, których nie ukrywa (choćby na końcu grida).

- [x] 8. Po wpisanie zmian w linijkach na samym końcu pliku, a następnie włączeniu na nich filtrowania i cofania zmian może duplikować ostatnią linijkę. Gdy przy zduplikowanej linijce wyłączy się filtrowanie program się wysypuje.

- [x] 9. Po wpisaniu zmian w linijkach na samym końcu pliku, a następnie włączeniu na nich filtrowania i cofania zmian może wyrzucić zaznaczenie linijki poza grida. Gdy w tym momencie utworzy się nową linijkę (prawy przycisk myszy) program się wysypie.
        -> Zamiast tworzyć linijkę prawym przyciskiem myszy można przejść na pole tekstowe i tam naciskając enter tworzyć linijki które nie wysypią programu, ale cofanie zmian w którymś momencie wysypuje program. Możliwe, że gdy dojdzie do momentu, gdy zaczęło się tworzyć linijki z pola tekstowego.

- [x] 10. Cofanie zmian ukrytym linijkom wyrzuca je z filtru. Otwarcie filtru i zamknięcie go nie przywraca tych linijek do filtru. Natomiast gdy po cofnięciu zmian wyłączy się filtrowanie i zacznie ponawiać zmiany linijki są ukrywane, bo wracają do nieistniejące filtru. Włączenie jakiegokolwiek filtru i wyłączenie filtrowania przywraca je do widoku.

- [x] 11. Filtrowanie według niepewnych ukrywa wszystkie linijki.

- [x] 12. Dopiero kombinacja według niepewnych i nieprzetłumaczonych filtruje tylko niepewne.

- [x] 13. Filtrowanie według zaznaczeń filtruje wszystko poza zaznaczonymi. Nie powinno być na odwrót?

- [x] 14. Wyłączenie filtrowania przy zaznaczonym odwróceniu filtrowania ukrywa wszystko.

- [x] 15. Wybranie opcji filtruj bez zaznaczenia konkretnych opcji filtrowania pokazuje pusty pasek po lewej stronie grida, gdzie normalnie znajdują się plusy do rozwijania filtrów.

- [x] 16. Filtruj napisałeś małą literą.

**Comment by kostek00** [comment]
- [ ] 17. Wyłączenie filtrowania z zaznaczonym odwróconym filtrowaniem ukrywa cały grid.

- [ ] 18. Ukrycie linijki zaraz przed lub za rozwiniętym filtrem dodaje ją do filtru i ukrywa ją. Cały filtr jest pokazany poza dodaną linijką. Dopiero naciśnięcie minusa pokazuję nowo ukrytą linijkę.

- [ ] 19. Ukrycie drugiej linijki po rozwiniętym filtrze, a następnie ukrycie linijki między dwoma filtra powoduje rysowanie plusa na poprzednim plusie bądź linii wskazującej obszar pierwszego filtra.
- [ ] I. Po zrobieniu powyższego zwinięcie pierwszego filtra powoduje ukrycie linijek w filtrze i pokazanie nowo dodanych do filtra.

- [ ] 20. Zwijanie i rozwijanie filtrów działa powoli. Między ukryciem i pokazanie linijek trzeba odczekać jakieś 0.5 sekundy zanim można wykonać inną akcję. (szybkie klikanie na plusa i minusa)

**Comment by bjakja** [comment]
Co do punktu 20 wyjaśnieniem jest to, co już maglowaliśmy z rozwijaną listą co drugie kliknięcie zwraca event dwukliku, wystarczy go tylko uwzględnić i powinno być ok,

**Comment by bjakja** [comment]
Co do punktów 17,18,19 to wszystkie załatałem po prostu sprawdzając czy przed albo za tym co ukrywamy nie ma widocznego bloku, wtedy zamiast ukrywać dodaję do widocznego bloku, tak że jeśli teraz coś poukrywasz i połączysz to z rozwiniętym drzewkiem to po prostu linia końcowa się przesunie i obejmnie wszystkie linijki. Może nie jest to rewelacyjne rozwiązanie ale nie mogą być dwa bloki bez przerwy choćby jednej linijki bo rozwijanie też będzie źle działać a także rysowanie + i - będzie świerować.

**Comment by bjakja** [comment]
Dodałem opcję z punktu pierwszego umożliwiającą wyłączenie resetu filtru, co do nazwy trzeba to jeszcze przedyskutować, ale sama opcja już działa poprawnie na tym co testowałem.
Dodałem także autofiltrowanie po otwarciu napisów, moje wybawienie w przypadku syfonapisów.

**Comment by bjakja** [comment]
Zaznaczyłem ostatni 9 punkt, bo zabezpieczyłem przekroczenie tablicy przy cofaniu/ponawianiu więc już raczej nie powinno się to wydarzyć, aczkolwiek to jest tylko blokada kraszy nie naprawia powodu wyjeżdżania aktywnej poza grid. Niniejszym zamykam ten rozbudowany issue dalsze błędy będziemy pisać w osobnych bo wszystko co tu jest opisane tyczyło się filtrowania.
