### ISSUE TITLE
"Delay relative to video" not support?

### ISSUE THREAD

**Issue by haiyang830** [bjakja/Kainote#259]
![a](https://user-images.githubusercontent.com/45539007/49683037-6d28ef00-faf9-11e8-98f4-b969494059d4.png)
video file:
[[HorribleSubs] Release the Spyce - 03 [720p].mkv](https://1.bitsend.jp/download/4e71ce62c2a246195a5f1af28a19aa5f.html)

**Comment by bjakja** [comment]
Most of new Horrible Subs releases have delay of 1 frame in Aegisub. After making typesetting and play it in normal player, subtitles made in Aegisub have Delay, cause it have constant 23.976 timecodes loaded in all files. Some peoples from Poland have the same problem. You can test some effects in player if timing works. When it will not work send me subs with lines timed to text on video in Aegisub and Kainote.

**Comment by bjakja** [comment]
About keyframes, I download this video and time something to keyframe and check if it works in player.

**Comment by haiyang830** [comment]
Thanks Reply,
Now I have no idea which display is correct, this is the subtitle of some frame, It's the same on VLC as Aegisub, and it's the same on Potplayer as Kainote.
![ddd](https://user-images.githubusercontent.com/45539007/49684753-ebde5600-fb12-11e8-8b09-6f25691bbe38.jpg)
![ccc](https://user-images.githubusercontent.com/45539007/49684755-f26ccd80-fb12-11e8-94ae-6c5ea83f1c00.jpg)
subtitle:
[test.zip](https://github.com/bjakja/Kainote/files/2659582/test.zip)

**Comment by bjakja** [comment]
I do not know either but one is correct here, this keyframes not match at all. Load this,
[[HorribleSubs] Release the Spyce - 03 [720p]_keyframes.txt](https://github.com/bjakja/Kainote/files/2659614/HorribleSubs.Release.the.Spyce.-.03.720p._keyframes.txt)
 and check like keyframes here should be.

**Comment by haiyang830** [comment]
I checked the keyframes, MPC and Kainote are the same. It seems to indeed be a problem with Aegisub. Sorry to bother you. Thank you!
