### ISSUE TITLE
Kainote does not support the new RFC 8081 font mimetypes

### ISSUE THREAD

**Issue by rctgamer3** [bjakja/Kainote#290]
As per [RFC 8081](https://tools.ietf.org/html/rfc8081), font mime types were standardised in 2017.

| extension |  mimetype |
|------------|-----------------|
otf | font/otf |
sfnt | font/sfnt |
ttf | font/ttf |
collection | font/collection |
woff | font/woff |
woff2 | font/woff2 |

I suggest adding support for these new mimetypes as listed [here](https://github.com/bjakja/Kainote/blob/master/Kaiplayer/MKVWrap.cpp#L390). MKVWrap.cpp only checks for ttf and otf. Don't replace them, just add the new ttf/otf ones, otherwise you will break (the) backwards compatibility.

Here's a quick suggestion:
```
if(mimetype == "font/ttf" || mimetype == "font/otf" || mimetype == "application/x-truetype-font" || mimetype == "application/vnd.ms-opentype"){
```

For reference, these are the now-deprecated ones:

- application/font-sfnt
- application/x-truetype-font
- application/x-font-opentype
- application/vnd.ms-opentype

**Comment by bjakja** [comment]
Good to know, I will add it later. 
Do you have any video to test these mimetypes? 
I would like to test this update, sometimes small fix make another huge bug.
