### ISSUE TITLE
problem with karaoke templater

### ISSUE THREAD

**Issue by ThePhantom00** [bjakja/Kainote#364]
I'm trying to apply template and i get errors but the same template works fine with Aegisub
![Image 60](https://user-images.githubusercontent.com/42273394/112230171-1c435300-8c3d-11eb-8754-b8760cc0c0b8.png)
U can test it

[Flames syl2end.zip](https://github.com/bjakja/Kainote/files/6193241/Flames.syl2end.zip)

**Comment by bjakja** [comment]
Is just the one line? 
Lua do not have "ke4" table, in Aegisub you have some additional library or they added something new recently.
It works on Aegisub 3.2.2?

**Comment by ThePhantom00** [comment]
yeah It works on Aegisub 3.2.2

**Comment by bjakja** [comment]
Thanks, I will check this on my Aegisub and find where it is implemented. It's not In executable for sure.

**Comment by bjakja** [comment]
This problem was caused by removing utils-auto4.lua that was only load to utils and automation opened only 1 file more for nothing. Rename just utils-auto4.lua to utils.lua.
