### ISSUE TITLE
Convert Menu Can not.

### ISSUE THREAD

**Issue by labrie75** [bjakja/Kainote#371]
v0.9.8.1292

Convert Menu Can not.

![Convert Menu](https://i.imgur.com/ys6VQJN.png)

**Comment by bjakja** [comment]
A small fix and it works again.
![obraz](https://user-images.githubusercontent.com/15655326/115198606-8a6f1e80-a0f2-11eb-86fd-bacc65e408df.png)
You can download fixed version from: https://drive.google.com/uc?id=1ECqsrLo5d1jPoz-FKvJrS0279YeTKrmS&export=download

**Comment by labrie75** [comment]
> A small fix and it works again.
> ![obraz](https://user-images.githubusercontent.com/15655326/115198606-8a6f1e80-a0f2-11eb-86fd-bacc65e408df.png)
> You can download fixed version from: https://drive.google.com/uc?id=1ECqsrLo5d1jPoz-FKvJrS0279YeTKrmS&export=download

Thank you.
