### ISSUE TITLE
With respect to the set key...

### ISSUE THREAD

**Issue by labrie75** [bjakja/Kainote#373]
In "Kainote", there are three choices when opening a file.(English Locale)
1.Mouse Click
2.CTRL-O
3.ALT-F->ALT-O

The first and second are the original methods.
But the third one is not commonly used.
Usually, the third way is...
ALT-F->O. This is how almost every program works.
In "Kainote" it is used differently.

Right click on the menu.

Typically, right-click and then presses the specified key specified.
But "Kainote" is executed only by right-clicking and pressing the ALT key and pressing the specified key.

Is it possible to modify "ALT-F->ALT-O" to behave like "ALT-F->O"?
Is it possible to modify "right click->ALT-key->key" to behave like "right click->key"?

**Comment by bjakja** [comment]
I see that context menu should draw "_" after opening without using Alt. 
By ALT-F->O you mean that after opening menu you release ALT and just push O key?
I don't know about "ALT properties". And it's custom menu, not from windows.

**Comment by labrie75** [comment]
Yes, that's right. 
That's how Aegisub works.
It has nothing to do with the underbar.

Press "alt-f", then press "o" without the "alt" key to open the File Open window.

**Comment by bjakja** [comment]
NOT that link, sorry.
https://drive.google.com/uc?id=1ECqsrLo5d1jPoz-FKvJrS0279YeTKrmS&export=download

**Comment by labrie75** [comment]
Thank you so much.
I requested it because it was different from the one I used, but thank you for correcting it.
It works well on Windows 10.
Will it be included in the next release?

Now I have to create a local Korean file.
:)

**Comment by bjakja** [comment]
It's good that you made this issue. If other thing not works right it should you can make an Issue. Bugs for me have highest priority.
When I publish a release it will contain every changes that I made in RTL branch. I have to write more fixes for Right To Left languages and than I make a Release. 
If you want to make a Korean translation of Kainote then I can add it to program and give you permission to send updates to Github.

**Comment by labrie75** [comment]
I'm still working on it.
Hangul has a different word order, and it takes some time to translate the functions that you don't understand into Hangul.

I'll let you know when it's done.

Thank you.
