### ISSUE TITLE
In the postprocessor, the lead-out does not work.

### ISSUE THREAD

**Issue by labrie75** [bjakja/Kainote#374]
lead-in
![in](https://user-images.githubusercontent.com/82786635/116210620-ffd79080-a77d-11eb-9deb-112c19ef72c1.png)

lead-out
![out](https://user-images.githubusercontent.com/82786635/116210638-036b1780-a77e-11eb-9388-c609523e6bad.png)

**Comment by bjakja** [comment]
I will check that, looks like something broke after snap to keyframes fixes.

**Comment by bjakja** [comment]
Fix for this bug is on Google Disk, link is the same, if you don't have it it's in project readme. I added your translation to that build. Later maybe I add automatic switch to locale using system locale.

**Comment by labrie75** [comment]
Thank you so much.
