### ISSUE TITLE
I'd like to upload a Korean localization file.

### ISSUE THREAD

**Issue by labrie75** [bjakja/Kainote#375]
I'd like to upload a Korean localization file.

I haven't done the explanation yet, but I think it's okay to distribute it because it's almost done.
I think you can do the rest slowly.

How can I add it?

**Comment by bjakja** [comment]
If you have program for git repository you can clone code and I give you an access to upload it to Github, If you do not used the program and don't know how to do it, then just upload files somewhere and give me the link I will do rest.
And I need better way of contact with you, mail or discord. Before release i need your update of translation.

**Comment by labrie75** [comment]
If you're authorized, code-add file-upload files Can I raise it to?

If so, it would be more convenient to give authority.

If not, I'd better send the file by email.

**Comment by bjakja** [comment]
You got an access. Upload 2 files mo and po, then I can add code that add to copy it with post build event, and add paths to packing program and should work. Just first upload translation.

**Comment by labrie75** [comment]
I uploaded it after fork.
Is this all I have to do?

**Comment by bjakja** [comment]
It's all. You have problems with translating of some lines? In file not all lines are translated.

**Comment by labrie75** [comment]
All right.
I didn't do it all.
I'm almost done with the menu, so it won't be a problem to use.

I'll finish the rest slowly.

**Comment by bjakja** [comment]
OK. If you have a problem to understand some texts or you found any weird texts that can have misspells write in it. The English translation was modified by few peoples and I don't verified every changes. I add your files in next Google release.

**Comment by bjakja** [comment]
I changed location of locale and for a week or more don't upload nothing, to avoid problem with merge. From now on it will pack using locale from solution locale, not locale from build. I do not have to change file by myself or change it via visual studio with every build.
