### ISSUE TITLE
I wish color the "\N" tag.

### ISSUE THREAD

**Issue by labrie75** [bjakja/Kainote#379]
![image](https://user-images.githubusercontent.com/82786635/116805565-49e7ba00-ab62-11eb-901b-54e66555cef9.png)

"KaiNote" on the left, "Aegisub" on the right.
It is difficult to distinguish because the "\N" tag does not contain colors.

**Comment by bjakja** [comment]
When I write the window I want to use bold for \N and this complicate everything but only different color is not a bad idea.

**Comment by labrie75** [comment]
Thank you. :)

**Comment by labrie75** [comment]
Thank you. :)

**Comment by labrie75** [comment]
After testing, there is a problem as below.
Can't we just tie the tags together?
"KaiNote" on the right, "Aegisub" on the left.
![Untitled-1](https://user-images.githubusercontent.com/82786635/116957082-e8465d80-acd1-11eb-9051-fd58a42e5ac1.jpg)

**Comment by bjakja** [comment]
I thought about it, just need to decrease value in line wrapper.
"{", "}" should work the same.

**Comment by labrie75** [comment]
Thank you very much for the correction.
