### ISSUE TITLE
Waveform crash after stretching

### ISSUE THREAD

**Issue by Rafawell** [bjakja/Kainote#380]
-Problem:
The program closes or stops responding and also closes immediately after stretching the waveform to the maximum (100%).

I'm using the latest version.

**Comment by bjakja** [comment]
By latest version you mean from Github. Get latest version from Google Disk build 1328 and try there, because I fixed similar bug.
Link: https://drive.google.com/uc?id=1ECqsrLo5d1jPoz-FKvJrS0279YeTKrmS&export=download

**Comment by Rafawell** [comment]
Yea! The recent version I said is the one I downloaded from Github ...
I checked it now and it seems to me that it is working perfectly ... 
I used 3 guides and I played stretching the audio and it didn't lock and much less closed!
Problem solved 😃!!!!!
Just one more favor, I could put the option of choosing between dark and light interface 😉

And thank you for your effort on this program, good work 😎👍
