### ISSUE TITLE
Add again "Video -> Use Dummpy Video..."

### ISSUE THREAD

**Issue by kedaitinh12** [bjakja/Kainote#385]
I seen it had in original ver aegisub, can you add this again. Cause i need it's for test some effect and it's don't lag than real video

**Comment by niskala5570** [comment]
![image](https://user-images.githubusercontent.com/34799053/124102541-0a224d80-da93-11eb-83ea-fa3b685c8de4.png)

**Comment by kedaitinh12** [comment]
Oh, sr i can't see it
