### ISSUE TITLE
Can't zoom video with scroll wheel mouse

### ISSUE THREAD

**Issue by kedaitinh12** [bjakja/Kainote#386]
In original ver aegisub, i just easy zoom video with scroll wheel mouse but in Kainote i can't. Were you removed it?

**Comment by niskala5570** [comment]
As stated in [FAQ](https://bjakja.github.io/NajczesciejzadawanepytaniaFAQ.html).
Hold down CTRL while mouse hover over the video for mouse wheel. Or just drag between sub box and video.
![resize](https://user-images.githubusercontent.com/34799053/124106344-b6196800-da96-11eb-8c7c-17f028dce375.gif)
It took me a while to figured out that too lol

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
I think it's good if turnback zoom video with only scroll wheel mouse

**Comment by bjakja** [comment]
Scroll is for audio volume control. And by "zoom" I understand always zoom of video frame instead of video window.
![obraz](https://user-images.githubusercontent.com/15655326/124130157-c291c680-da7e-11eb-8d08-ae89ed103fb7.png)

**Comment by niskala5570** [comment]
I don't think its a bother tho. I'm fine with this.

**Comment by bjakja** [comment]
This zoom was made for typesetting and without it making vector drawings and clips is nightmare.

**Comment by kedaitinh12** [comment]
You right

**Comment by kedaitinh12** [comment]
I think don't need back zoom video with scroll wheel mouse again
