### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by Rafawell** [bjakja/Kainote#393]
Well be in doubt where to write, so I'll write here 😀

I could add the option "next line with the video call for that moment" 
because every time I have to double click, I haven't even found a shortcut to it 😥

Thanks!!!
I'm learning about .ass thanks to this program 😊

**Comment by bjakja** [comment]
You want tat option from Aegisub? Click on line + change line goes to video for this moment. It's already added, on list below video. 
![obraz](https://user-images.githubusercontent.com/15655326/126812107-0529eb53-b5d2-4ab0-9d70-665cd4f4852c.png)
You can also click on line number column it always changes video position after click. Shift + click for set end time. I do not know about any shortcut for set video position for active line, there is only option for shortcut for set line start position on audio.

**Comment by Rafawell** [comment]
Bro thank you very much 😀
I haven't fully explored the program yet, 
and it doesn't even need a hotkey, it's great for me!

I just miss a little that it could have a light color theme, 
my vision is a mess 😁

Thanks @bjakja 👍
