### ISSUE TITLE
Wymagane biblioteki

### ISSUE THREAD

**Issue by r1n0x** [bjakja/Kainote#396]
Zdażyło mi sie spotkać osobe której Kainote się nie odpalał (0xc00007b) na fresh komputerze z W10.

Dałem jej 3 biblioteki i któraś z nich pomogła, ty raczej wiesz która to biblioteka, osobiscie sugeruje dodac linka do README do wymaganej biblioteki

Linki które dałem tej osobie:
https://www.microsoft.com/pl-pl/download/confirmation.aspx?id=53344
https://aka.ms/vs/16/release/vc_redist.x64.exe
https://www.microsoft.com/en-us/download/confirmation.aspx?id=20914

Dzięki za tworzenie Kainote, szczególnie za funkcje Kolejkcjonera Czcionek, bardzo mi ułatwia życie jako osobie która wypala odcinki <3

**Comment by bjakja** [comment]
Znów musieli wymyślić coś, żeby utrudnić mi robotę, na vs 2017 nie było żadnych problemów, cóż, wyeliminować to jest ciężko, gdybyś chociaż wiedział co zainstalował z tych linków, bo raczej framework jest niepotrzebny, prędzej z redista czegoś brakuje.
Ogólnie to wolałbym dać ten dll do paczki, ale bez reinstalu systemu ciężko będzie to odkryć.
ale jak nadarzy się okazja to zrobię odpowiedni update.
