### ISSUE TITLE
New ver ffms2 can fix DNXHD and new updates in the present

### ISSUE THREAD

**Issue by kedaitinh12** [bjakja/Kainote#397]
Can you update new ver ffms2 in Kainote?? Thanks
https://forum.doom9.org/showthread.php?p=1949799#post1949799

**Comment by bjakja** [comment]
If you test it, and works with Kainote then I can update it.

**Comment by kedaitinh12** [comment]
> If you test it, and works with Kainote then I can update it.

I added and test again, it's seem work with DNXHD
You can see here, ffms2 perfome same L-SMASH Source
https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/commit/e5bb1ecb71f0edb5b7632b1013faaed77277e2b4#commitcomment-54664734

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
This unofficial now has source code:
https://codeberg.org/StvG/ffms2/src/branch/doom9
Seeking test with unofficial and official (click to open image), video files to test here:
https://forum.doom9.org/showthread.php?p=1992736#post1992736
