### ISSUE TITLE
When will there be a new version of Kainote

### ISSUE THREAD

**Issue by malzen** [bjakja/Kainote#403]
I would like to know when you are going to make a version as you have not made any update since Aug.

**Comment by bjakja** [comment]
I think that is still incomplete to public release. You can download beta version from Google Disk. I know, that I don't make any new beta versions from months it's because of my sickness.

**Comment by malzen** [comment]
That's ok I understand. Can you give me the link to the beta version please.

**Comment by kedaitinh12** [comment]
Hi bjakja, are you fine??

**Comment by mmaku89** [comment]
He is better now, but still recovering. He needs more time.

**Comment by kedaitinh12** [comment]
Oh, i think he to get COVID (maybe), hope him better

**Comment by bjakja** [comment]
Covid was part of it, main sickness is much worse, sorry for my English, I "learning" it second time.

**Comment by malzen** [comment]
Hope you are feeling better.
Take your time.

**Comment by kedaitinh12** [comment]
> 

oh, hope you better

**Comment by bjakja** [comment]
Hello everyone, i'm feeling better day by day. I'm learning to live again after severe depression.

**Comment by bjakja** [comment]
Yes, I know that I create this program, so this is the end of topic.
