### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [bjakja/Kainote#414]
https://hosted.weblate.org/projects/kainote/kainote/#information says GPLv3-only, but
[this](https://github.com/bjakja/Kainote/blob/2e19f1fd59921dcc9d8a49e7a950006f064c4d35/Kaiplayer/NewCatalog.h) says GPLv3-or-later, with more examples in https://github.com/bjakja/Kainote/search?q=any+later+version

It can be changed from GPLv3- to GPLv3+ in
https://hosted.weblate.org/settings/kainote/kainote

**Comment by altinat** [comment]
Thank you for notifying 
It was my own mistake. I'll fix it ASAP
