### ISSUE TITLE
Instalacja na Windows 7.

### ISSUE THREAD

**Issue by ThomasLeigh** [bjakja/Kainote#422]
Czy jest możliwa instalacja programu oraz jego używanie na Windows 7 32-bit? Próbowałem:

1. Uruchomić program w trybie zgodności z Windows 7.
2. Doinstalować directx_Jun2010_redist.exe .

Niestety nie pomogło. Zawsze pojawia się następujący komunikat:

„KaiNote.exe - Zły obraz
---------------------------
Program ...\Kainote\MSVCP140.dll nie jest przeznaczony do uruchamiania w systemie Windows albo zawiera błąd. Zainstaluj program ponownie, używając oryginalnego nośnika instalacyjnego, albo skontaktuj się z administratorem systemu lub z dostawcą oprogramowania w celu uzyskania pomocy”.

**Comment by bjakja** [comment]
należy pobrać wersję starszą z wersją x32 https://github.com/bjakja/Kainote/releases/download/v0.9.9.1397/Kainote.x86.zip
np taką
a mvsvp140 jeśli nie ma to mogę ci podesłać

**Comment by ThomasLeigh** [comment]
Dziękuję za chęć pomocy. A którą starszą wersję Kainote polecasz sprawdzić w moim przypadku (gdyż v0.9.9.1397 jest najnowsza)?

**Comment by bjakja** [comment]
I to ona nie działa, co jest naprawdę bardzo dziwne
bo na pewno powinna działać na win7

**Comment by ThomasLeigh** [comment]
Z poprzednią wersją to samo :( . Co do msvcp140.dll - ten plik jest, ale komunikat wyrzuca że "nie jest przeznaczony do uruchamiania w systemie Windows albo zawiera błąd".

**Comment by bjakja** [comment]
to podrzucę wersję z systemu 32

**Comment by bjakja** [comment]
Próbowałeś instalować redist 2015 - 2022?
i wywal ten nie działający plik

**Comment by ThomasLeigh** [comment]
> Próbowałeś instalować redist 2015 - 2022?

Nie, już szukam...

**Comment by bjakja** [comment]
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
tego spróbuj

**Comment by ThomasLeigh** [comment]
Zainstalowałem redist z powyższego linku - restart komputera, bez zmian. Usunąłem plik msvcp140.dll i program się uruchomił, pytanie tylko czy brak tego pliku nie będzie istotnym problemem?

**Comment by bjakja** [comment]
nie, bo go zainstalowałeś, możliwe że zły włożyłem po prostu i x64 z x32 nie będzie działać poprawnie, ale nikt tego nie zgłaszał, ale niestety wycofałem się z wersji x32 i nie będę każdego relejsu poprawiał

**Comment by ThomasLeigh** [comment]
A do czego służy ten plik mvsvp140?

Masz na myśli iż nie będziesz rozwijał wersji x32 :( ?

**Comment by bjakja** [comment]
Tak tylko wersje x64 w z  wsparciem różnych instrukcji procesora, ale jak chcesz to ci mogę zrobić na specjalne zamówienie najnowszą wersję jak będzie kompletna Kainote nitro x32

**Comment by ThomasLeigh** [comment]
Dziękuję Ci za całą - tak szybką oraz elastyczną (TeamViewer, Discord - obce mi, ale bardzo doceniam) - pomoc. Ogromna niespodzianka z możliwością wersji x32 "na zamówienie" - z pewnością się piszę.

**Comment by bjakja** [comment]
Tylko jeszcze muszę trochę problemów rozwiązać, ale też zależy do czego będziesz używał programu

**Comment by ThomasLeigh** [comment]
> zależy do czego będziesz używał programu

Czy mógłbyś rozwinąć tą myśl?

**Comment by bjakja** [comment]
Czy do tłumaczenia, czy do dopasowania napisów, typesettingu, robienia karaoke, timingu audio, trochę jest możliwości.

**Comment by ThomasLeigh** [comment]
Zajmuję się wprowadzaniem napisów do istniejącego materiału wideo lub samego audio z nieruchowym obrazkiem jako pseudo-wideo - uwzględniając różne pozycje napisów na ekranie oraz różny wygląd (używam .ass).

Do tej pory korzystałem z programu Subtitle Edit, jednak niedawno dowiedziałem się o Twoim programie i odniosłem wrażenie, że mógłby być lepszy, zwłaszcza jeśli chodzi o wspomniane pozycjonowanie napisów na ekranie - stąd zdecydowałem się spróbować. Czy w takim przypadku brak owego pliku mi nie przeszkodzi?

**Comment by bjakja** [comment]
na pewno ci nie przeszkodzi, bo go zainstalowałeś do systemu. W folderze Kainote już jest niepotrzebny
