### ISSUE TITLE
Skalowanie interfejsu.

### ISSUE THREAD

**Issue by ThomasLeigh** [bjakja/Kainote#423]
Używam rozdzielczości 1680x1050. Jako że wzrok słabszy, interfejs programu jest dla mnie malutki, ciężki w użytkowaniu. Czy byłaby możliwość wprowadzenia opcji skalowania interfejsu o różne lub dowolne współczynniki?

**Comment by bjakja** [comment]
w sensie chcesz powiększyć wideo
to użyj ctrl+rolka myszy na wideo
chcesz zwiększyć czcionkę w całym programie użyj opcji zaraz pokażę na obrazku
![obraz](https://user-images.githubusercontent.com/15655326/171055787-72ccb7f7-8f38-45b5-accb-ee6171eca075.png)

**Comment by ThomasLeigh** [comment]
Fakt, dziękuję, świetnie że da się to zrobić. Czy można by jeszcze powiększyć ikonki ustawione pionowo po lewej w oknie programu?

Mała uwaga:
Jeśli za bardzo powiększy się font samego GUI, w oknie ustawień programu może nie mieścić się przycisk zastosowania zmian - a samo okno sprawia wrażenie jakby nie dawało się skalować myszką. Z opresji uratował mnie plik Config.txt :)

**Comment by bjakja** [comment]
i tu jest trochę cianko bo ikony powiększone wyglądają jak ciapry, dlatego też nie ma narazie opcji ich skalowania bo muszą być 2 komplety ale nie ma kto ich zrobić, bo ja ich nie robiłem.

**Comment by ThomasLeigh** [comment]
Czy zmianą czcionki programu można pokryć również etykiety widoczne po najechaniu (na ikonkę, na pozycję w ustawieniach...)? Aktualnie jej nie podlegają.

**Comment by bjakja** [comment]
tylko odstępy między ikonami się zmieniają, ale ikon nie można skalować to się bardzo niewyraźne robią najlepszym rozwiązaniem jest zrobienie wszystkich ikon w svg ale nie mam do tego możliwości technicznych bo grafikiem nie jestem

**Comment by ThomasLeigh** [comment]
A czy tooltipy (opisy pojawiające się po najechaniu myszką czy to na ikonkę, czy na jakąś pozycję w ustawieniach programu - patrz obrazek niżej) można by objąć wielkością czcionki programu?

![sshot-2](https://user-images.githubusercontent.com/26142231/171124015-e9b4d727-bb87-42cd-8726-c8e9b5741376.png)

**Comment by bjakja** [comment]
To jest jeszcze windowsowskie, tak że wielkiego wpłytu nie mam, ale będę pisał swoje tooltipy kiedyś
