### ISSUE TITLE
Niepedantycznie precyzyjne wstawianie czasu wideo jako początkowy/końcowy napisu.

### ISSUE THREAD

**Issue by ThomasLeigh** [bjakja/Kainote#432]
Jeśli przykładowo mam wideo zapauzowane na 00:15:47:820, to jeśli chcę wstawić ten czas jako koniec bieżącego napisu (skrótem Ctrl+strzałka w prawo), końcówka "820" zostanie wstawiona o jako "830"; w przypadku czasu początkowego (Ctrl+strzałka w lewo) jako "810".

**Comment by ThomasLeigh** [comment]
Czy mogę zapytać, dlaczego? Do tej pory myślałem że to właśnie ustawianie napisów pedantycznie z klatkami daje najlepszy, perfekcjonistyczny efekt.

**Comment by bjakja** [comment]
a no dlatego bo jak się trafi dokładnie taki czas jak klatka to się źle kończy albo zaczyna, szczególnie na direct show ale na ffms2 też się zdarza.
Normalnie to występuje tylko przy skryptach, które próbują robić efekt co klatkę albo jakiś zbliżony interwał.
