### ISSUE TITLE
Nazwy screenshotów

### ISSUE THREAD

**Issue by Shou-nen** [bjakja/Kainote#442]
Program umożliwia zapisywanie zrzutów ekranu, ale po dziesiątym resetuje się numeracja - jak na zdjęciu poniżej (posortowane wg daty wykonania, a nie nazwy).

![image](https://user-images.githubusercontent.com/53655415/208631516-c3bc699f-7bc1-462d-96e0-35604445e0d5.png)

**Comment by bjakja** [comment]
Błąd naprawiony
